defaults:
    - dataset: 2019/english
    - preprocessing: default
    - model: default

checkpoint: /Users/gt/Documents/GitHub/ZeroSpeech/ckpt
out_dir: /Users/gt/Documents/GitHub/ZeroSpeech/outdir
save_auxiliary: False